const SIZE = 20;
const TRIALS = 100;
const STEP = 0.05;
const MARGIN = 50;
const PERCOLATION_THRESHOLD = 0.593;
const WINDOW_WIDTH = window.innerWidth - 32;
const GRID_DIMENSIONS = WINDOW_WIDTH < 400 ? WINDOW_WIDTH : 400;
const SITE_DIMENSIONS = GRID_DIMENSIONS / SIZE;

export {
  SIZE,
  TRIALS,
  STEP,
  MARGIN,
  PERCOLATION_THRESHOLD,
  GRID_DIMENSIONS,
  SITE_DIMENSIONS,
};
